spring:
  application:
    name: TinProjectSp

  datasource:
    url: jdbc:h2:file:./data/itn_db
    driver-class-name: org.h2.Driver
    username: tin
    password: itn

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    org.hibernate.SQL: debug

